#!/bin/bash

mydir=$(cd "$(dirname "$0")"; pwd)
. "${mydir}/http_functions"
. "${mydir}/screentime_functions"

user="$QUERY_STRING"
http_error_400_if_invalid_username "$user" "Username"

time_dir="/var/local/screentime"
remaining=$(get_screentime_remaining "${time_dir}" "${user}")
http_error_404_if_invalid_counter "$user" "$?" "$remaining"

decrease_if_positive "${time_dir}" "${user}" "${remaining}"

log_file="/var/log/webfs/screentime.log"
logged_http_response "${remaining}" "${log_file}"
