#!/bin/bash

function get_screentime_remaining() { # 1:screentime_dir, 2:user
  local dir="${1}/${2}"
  cd "${dir}" && {
    local x="$(ls)"
    echo "${x}"
  }
}

function decrease_if_positive() { # 1:timedir 2:user 3:counter
  local x=$3
  test $x -gt 0 && {
    cd "$1/$2"
    mv "$x" "$[x-1]"
  }
}




