#!/bin/bash

http_response() {
  echo "Status: 200 OK"
  echo "Content-type: text/plain"
  echo
  echo "$1"
  exit 0
}

http_error() {
  echo "Status: $1 $2"
  echo "Content-type: text/plain"
  echo
  echo "$3"
  exit 1
}

user="$QUERY_STRING"

if [ -z "$user" ]; then 
  http_error 400 "Bad request" "Empty query string"
fi

if [[ ! "$user" =~ ^[a-z0-9]{1,10}$ ]]; then
  http_error 400 "Bad request" "Illegal characters in username: $user" 
fi

dir="/var/local/screentime/$user"

if [ ! -d "$dir" ]; then
  http_error 404 "Not Found" "Unknown user: $user"
fi

cd "$dir"
x="$(ls)"

# fail if no number 
if [ ! "$x" -eq "$x" ]; then
  http_error 404 "Not Found" "No screentime counter found for user: $user"
fi

# decrease if positive
if [ "$x" -gt "0" ]; then 
  mv "${x}" "$[x-1]"
fi

echo "$(date --rfc-3339 seconds) : ${x}" >> /var/log/webfs/screentime.log

http_response "${x}"
